module aes_accelerator_top (
    input  wire         clk,          // System Clock (e.g., 50 MHz)
    input  wire         rst_btn,      // Hardware Reset Button (Active High)

    //----------------------------------------------------------
    // UART Interface (Physical)
    //----------------------------------------------------------
    input  wire         uart_rxd,     // Serial Input
    output wire         uart_txd      // Serial Output
);

    //----------------------------------------------------------------
    // 1. Internal Signals & Interconnects
    //----------------------------------------------------------------
    
    // Reset Network
    wire rst_sys_safe;
    wire soft_rst_pulse;     // Generated by Main FSM
    wire combined_rst;       // Hardware + Software Reset

    // FIFO Connections (Main FSM <-> UART Top)
    wire [151:0] main_rx_data;
    wire         main_rx_rd_en;
    wire         main_rx_empty;

    wire [151:0] main_tx_data;
    wire         main_tx_wr_en;
    wire         main_tx_full;

    // Key Expansion Signals
    wire [127:0] key_config_data;
    wire         key_go_sig;
    wire         key_done_sig;
    wire [127:0] active_round_keys [0:10];

    // AES Input FIFO (Main FSM -> AES FSM)
    wire [151:0] aes_in_wdata;
    wire         aes_in_w_en;
    wire         aes_in_full;
    wire [151:0] aes_in_packet;
    wire         en_ififo_wire;
    wire         aes_in_empty_wire;

    // AES Output FIFO (AES FSM -> Main FSM)
    wire [151:0] aes_out_rdata;
    wire         aes_out_r_en;
    wire         aes_out_empty;
    wire [151:0] aes_out_packet;
    wire         en_ofifo_wire;
    wire         aes_out_full_wire;

    // Control
    wire sys_enable_sig;

    //----------------------------------------------------------------
    // 2. Reset Synchronization Logic
    //----------------------------------------------------------------
    assign combined_rst = rst_btn | soft_rst_pulse;

    // Synchronize Reset for System Domain
    reset_sync u_rst_sys (
        .clk(clk),
        .rst_in(combined_rst),
        .rst_out(rst_sys_safe)
    );

    //----------------------------------------------------------------
    // 3. UART Top Level (Replaces Simulation Buffers)
    //----------------------------------------------------------------
    // This module handles physical UART <-> Packet Assembly <-> FIFOs
    // It provides the exact interface needed by the Main FSM.
    
    top_uart u_uart_interface (
        .clk(clk),
        .reset_n(~rst_sys_safe), // UART module uses Active Low reset
        
        // Physical Pins
        .uart_rxd(uart_rxd),
        .uart_txd(uart_txd),
        
        // RX FIFO Interface (Read by Main FSM)
        .rx_fifo_read_en(main_rx_rd_en),
        .rx_fifo_data_out(main_rx_data),
        .rx_fifo_empty(main_rx_empty),
        
        // TX FIFO Interface (Written by Main FSM)
        .tx_fifo_write_en(main_tx_wr_en),
        .tx_fifo_data_in(main_tx_data),
        .tx_fifo_full(main_tx_full),
        
        .tx_active() // Open (unused in logic)
    );

    //----------------------------------------------------------------
    // 4. Main FSM (The "Router")
    //----------------------------------------------------------------
    main_fsm u_main_fsm (
        .clk(clk),
        .rst(rst_sys_safe),

        // RX Interface (From UART)
        .rx_data(main_rx_data),
        .rx_empty(main_rx_empty),
        .rx_rd_en(main_rx_rd_en),

        // TX Interface (To UART)
        .tx_data(main_tx_data),
        .tx_wr_en(main_tx_wr_en),
        .tx_full(main_tx_full),

        // Key Expansion Interface
        .key_in(key_config_data),
        .key_go(key_go_sig),
        .key_done(key_done_sig),

        // AES Input FIFO Interface
        .aes_in_data(aes_in_wdata),
        .aes_in_wr_en(aes_in_w_en),
        .aes_in_full(aes_in_full),

        // AES Output FIFO Interface
        .aes_out_data(aes_out_rdata),
        .aes_out_empty(aes_out_empty),
        .aes_out_rd_en(aes_out_r_en),

        // Controls
        .sys_enable(sys_enable_sig),
        .soft_rst(soft_rst_pulse)
    );

    //----------------------------------------------------------------
    // 5. Key Expansion Module
    //----------------------------------------------------------------
    key_expansion_fsm u_key_expan (
        .clk(clk),
        .rst(rst_sys_safe),
        .go(key_go_sig),
        .key_in(key_config_data),
        .done(key_done_sig),
        .round_keys(active_round_keys)
    );

    //----------------------------------------------------------------
    // 6. AES Processing Layer (FIFOs + FSM)
    //----------------------------------------------------------------
    
    // AES Input Buffer (Main FSM -> AES FSM)
    // NOTE: Uses the same async_fifo definition provided in UART modules
    async_fifo #(.WIDTH(152), .DEPTH(16)) u_aes_in_fifo (
        .wclk(clk), .wrst(rst_sys_safe),
        .w_en(aes_in_w_en), .wdata(aes_in_wdata), .full(aes_in_full),
        
        .rclk(clk), .rrst(rst_sys_safe),
        .r_en(en_ififo_wire), .rdata(aes_in_packet), .empty(aes_in_empty_wire)
    );

    // The AES FSM
    aes_fsm u_aes_fsm (
        .clk(clk),
        .rst(rst_sys_safe),
        .start(key_done_sig),            // Enabled only when keys are ready
        
        .input_fifo_empty(aes_in_empty_wire),
        .output_fifo_full(aes_out_full_wire),
        
        .round_keys(active_round_keys),
        .input_packet(aes_in_packet),
        
        .output_packet(aes_out_packet),
        .valid(),                        // valid is implicit in FIFO write enable (en_ofifo)
        
        .en_ififo(en_ififo_wire),
        .en_ofifo(en_ofifo_wire),
        
        .rst_ififo(), 
        .rst_ofifo()  
    );

    // AES Output Buffer (AES FSM -> Main FSM)
    async_fifo #(.WIDTH(152), .DEPTH(16)) u_aes_out_fifo (
        .wclk(clk), .wrst(rst_sys_safe),
        .w_en(en_ofifo_wire), .wdata(aes_out_packet), .full(aes_out_full_wire),
        
        .rclk(clk), .rrst(rst_sys_safe),
        .r_en(aes_out_r_en), .rdata(aes_out_rdata), .empty(aes_out_empty)
    );

endmodule


//----------------------------------------------------------------
// Helper: Reset Synchronizer
//----------------------------------------------------------------
module reset_sync (
    input  wire clk,
    input  wire rst_in,
    output reg  rst_out
);
    reg rst_meta;
    always @(posedge clk or posedge rst_in) begin
        if (rst_in) begin
            rst_meta <= 1;
            rst_out  <= 1;
        end else begin
            rst_meta <= 0;
            rst_out  <= rst_meta;
        end
    end
endmodule